In [3]:
import torch
temp = torch.rand(3,4)
print(temp)
## Tensor Index Operations 
# temp[n_start:n_end ,col_index] 


tensor([[0.3883, 0.1711, 0.3019, 0.8506],
        [0.7548, 0.7739, 0.7363, 0.0904],
        [0.0661, 0.8832, 0.2725, 0.1249]])


In [4]:
## Example 1
# Using only n_start and n_end
print(temp[1:3])

tensor([[0.7548, 0.7739, 0.7363, 0.0904],
        [0.0661, 0.8832, 0.2725, 0.1249]])


In [6]:
## Example 2
# Using only col_index
print(temp[:,0])

tensor([0.3883, 0.7548, 0.0661])


In [7]:
## Example 2
# Using only col_index (2)
print(temp[:,1])

tensor([0.1711, 0.7739, 0.8832])


In [8]:
## Example 3
# Combination of rows and columns
print(temp[1:3,1])

tensor([0.7739, 0.8832])


## Multiplication in Tensors 

In [23]:
a = torch.rand(10,5)
b = torch.rand(15,5)
print(a)
print(b)

tensor([[0.4062, 0.1288, 0.9479, 0.7606, 0.7687],
        [0.6894, 0.6732, 0.4078, 0.9193, 0.2529],
        [0.5474, 0.5912, 0.4643, 0.7362, 0.3831],
        [0.4902, 0.7123, 0.6613, 0.7025, 0.7801],
        [0.8417, 0.3052, 0.4589, 0.3867, 0.4824],
        [0.7735, 0.6451, 0.2695, 0.9179, 0.9588],
        [0.5020, 0.4784, 0.2725, 0.5096, 0.9241],
        [0.8759, 0.0198, 0.1717, 0.3793, 0.0825],
        [0.9604, 0.5778, 0.1468, 0.5079, 0.1433],
        [0.9941, 0.4681, 0.4563, 0.5787, 0.2818]])
tensor([[0.4603, 0.0854, 0.3640, 0.9114, 0.5792],
        [0.1741, 0.5159, 0.9093, 0.9907, 0.9391],
        [0.6767, 0.2190, 0.7759, 0.3953, 0.9994],
        [0.0991, 0.1404, 0.0509, 0.0351, 0.2772],
        [0.2885, 0.2388, 0.7491, 0.3645, 0.4451],
        [0.0697, 0.9169, 0.6411, 0.0372, 0.8197],
        [0.6227, 0.3181, 0.5320, 0.8742, 0.0772],
        [0.4166, 0.4283, 0.0393, 0.6764, 0.0237],
        [0.3884, 0.2123, 0.0918, 0.4530, 0.0286],
        [0.9466, 0.3629, 0.8823, 0.8767, 0.7777],