# A notebook to visualize and understand how Embedding works and try out some things

In [39]:
import torch

In [83]:
n_users=10
n_movies=8
n_factors = 5

user_factors = torch.nn.Embedding(n_users , n_factors)
movie_factors = torch.nn.Embedding(n_movies , n_factors)

print("Movies Embedding :" , movie_factors.weight.shape)
print(movie_factors.weight)

print("User Embedding :",user_factors.weight.shape)
print(user_factors.weight)

Movies Embedding : torch.Size([8, 5])
Parameter containing:
tensor([[-1.0224e+00,  7.7765e-01, -1.7292e+00, -6.0225e-01,  1.3205e+00],
        [ 5.0167e-01,  4.2531e-01, -7.2910e-01,  1.3605e-01,  1.3146e+00],
        [ 5.8751e-02,  5.3420e-01, -1.1324e+00, -5.9317e-01, -1.6992e-03],
        [-1.4291e-01, -4.2862e-01, -1.2593e+00, -1.0713e+00,  3.0666e-01],
        [-7.0405e-01,  2.3527e-01, -1.4152e+00,  9.1666e-02, -5.3713e-01],
        [ 7.1883e-01, -8.1998e-01,  8.1300e-01,  3.8109e-01, -1.3744e+00],
        [ 7.9027e-01, -1.0999e+00, -5.9524e-01,  1.4957e+00,  6.2148e-01],
        [ 5.3431e-01,  2.9356e-02,  1.3172e-01, -5.4032e-01, -2.8683e-01]],
       requires_grad=True)
User Embedding : torch.Size([10, 5])
Parameter containing:
tensor([[-1.7936,  0.8009, -0.1172,  1.0408,  0.1826],
        [ 0.3929,  0.6648,  0.5748,  0.1417, -0.1654],
        [-0.2205, -0.1150,  0.7574, -0.8701,  0.9573],
        [ 0.5695, -0.2393,  1.3662,  0.5835,  0.3833],
        [-0.5533, -0.6992, -1.452

### See what goes inside the forward prop

In [82]:
n_entries = 100
user_ids = torch.tensor(range(n_users)).reshape(n_users,1)
movie_ids =torch.tensor([i for i in range(n_movies)]).reshape(n_movies,1)
x = torch.cat((user_ids, movie_ids), 1)
x

RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 10 and 8 in dimension 0 (The offending index is 1)

In [51]:
x[1:2,0] = 9

In [52]:
print(x[:,0])
print(x[:,1])

tensor([0, 9, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


In [53]:
users = user_factors(x[:,0])
users

tensor([[ 1.8690, -0.4804,  1.7336,  1.9536, -0.8210],
        [-1.4040,  0.4420, -0.6059,  0.4778, -0.1344],
        [-1.3346, -0.9378, -0.0837, -0.3786, -1.6721],
        [-1.0683,  1.3972, -0.3341, -0.7199, -0.7841],
        [ 0.4318,  1.1973,  1.0880,  1.6442,  0.2318],
        [-0.1375,  0.1788, -0.2875,  1.5874, -0.0398],
        [-0.1507, -0.0549, -0.6437, -0.1132,  3.0500],
        [-2.0243,  1.0269, -0.6970,  2.2008,  1.3098],
        [ 2.1442,  0.0438,  1.0159, -0.5385, -0.7016],
        [-1.4040,  0.4420, -0.6059,  0.4778, -0.1344]],
       grad_fn=<EmbeddingBackward>)

In [45]:
user_factors.weight

Parameter containing:
tensor([[ 1.8690, -0.4804,  1.7336,  1.9536, -0.8210],
        [ 0.6193, -0.9607,  1.7446, -0.8447,  0.5813],
        [-1.3346, -0.9378, -0.0837, -0.3786, -1.6721],
        [-1.0683,  1.3972, -0.3341, -0.7199, -0.7841],
        [ 0.4318,  1.1973,  1.0880,  1.6442,  0.2318],
        [-0.1375,  0.1788, -0.2875,  1.5874, -0.0398],
        [-0.1507, -0.0549, -0.6437, -0.1132,  3.0500],
        [-2.0243,  1.0269, -0.6970,  2.2008,  1.3098],
        [ 2.1442,  0.0438,  1.0159, -0.5385, -0.7016],
        [-1.4040,  0.4420, -0.6059,  0.4778, -0.1344]], requires_grad=True)

In [54]:
## Shows out of range since embedding is defined only till n_movies and the inputed is greater
movies = movie_factors(x[:,1])

IndexError: index out of range in self

In [68]:
x[:,1] = torch.tensor(range(n_movies))
## Changing entries of the third row
x[2:3,1] = 8
x

tensor([[0, 0],
        [9, 1],
        [2, 8],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

In [69]:
movies = movie_factors(x[:,1])
print("Look at the thrid row to see the difference ")
movies

Look at the thrid row to see the difference 


tensor([[-0.4689, -0.7337, -0.3200,  0.7721, -0.4577],
        [ 0.1933, -0.0187, -1.1271, -1.0587, -0.9241],
        [ 0.7221,  0.5769, -1.1651, -1.2481, -0.6516],
        [-1.3625,  1.6580, -0.8540,  1.0999, -1.1263],
        [ 0.5616, -0.7726, -0.2238,  1.1252, -0.6559],
        [ 0.1982,  0.1515,  1.1382,  0.8855,  0.8914],
        [-0.8765,  0.8940,  0.5413,  0.2371,  0.4993],
        [-0.4090, -0.9693,  1.4013,  0.3986, -1.1957],
        [ 0.7221,  0.5769, -1.1651, -1.2481, -0.6516],
        [ 0.7599, -2.4699, -0.1512,  0.2937,  1.1726]],
       grad_fn=<EmbeddingBackward>)

In [70]:
print("Look at the thrid row to see the difference ")
movie_factors.weight

Look at the thrid row to see the difference 


Parameter containing:
tensor([[-0.4689, -0.7337, -0.3200,  0.7721, -0.4577],
        [ 0.1933, -0.0187, -1.1271, -1.0587, -0.9241],
        [ 0.2076, -1.7650,  1.3562, -0.6355, -0.0279],
        [-1.3625,  1.6580, -0.8540,  1.0999, -1.1263],
        [ 0.5616, -0.7726, -0.2238,  1.1252, -0.6559],
        [ 0.1982,  0.1515,  1.1382,  0.8855,  0.8914],
        [-0.8765,  0.8940,  0.5413,  0.2371,  0.4993],
        [-0.4090, -0.9693,  1.4013,  0.3986, -1.1957],
        [ 0.7221,  0.5769, -1.1651, -1.2481, -0.6516],
        [ 0.7599, -2.4699, -0.1512,  0.2937,  1.1726]], requires_grad=True)

In [73]:
users.shape , movies.shape

(torch.Size([10, 5]), torch.Size([10, 5]))

In [76]:
ratings = (users*movies).sum(dim = 1)

In [77]:
class DotProduct(torch.nn.Module):
    def __init__(self,n_users , n_movies ,n_factors):
        self.user_factors = torch.nn.Embedding(n_users,n_factors)
        self.movies_factors = torch.nn.Embedding(n_movies,n_factors)
    
    def forward(self,input_x):
        users = self.user_factors(input_x[:,0])
        movies = self.user_factors(input_x[:,1])
        
        # Note : users and movies would be of the same shape (n_rows , n_factors) , where n_rows is the number of entires in a batch
        
        ratings = (users*movies).sum(dim=1)
        return ratings
